# Generated by Django 5.2.13 on 2026-04-28 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
                ('dataNasc', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=30)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('depto', models.IntegerField(blank=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='core.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='core.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('dataInicioGerencia', models.DateField()),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gerencia_depto', to='core.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('localizacao', models.CharField(max_length=45)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('matric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empregado')),
                ('codProj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projeto')),
            ],
        ),
    ]
